# Generated by Django 5.2 on 2025-04-28 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='infoextra',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
