# Generated by Django 5.2 on 2025-04-28 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_cliente_alter_cortepelo_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesional',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='profesionales'),
        ),
    ]
