# Generated by Django 5.2 on 2025-04-28 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_profesional_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesional',
            name='fecha_ingreso',
            field=models.DateField(blank=True, null=True),
        ),
    ]
